web:
  build: ./app
  volumes:
    - "app:/src/app"
  expose:
    - "3000"
  links:
    - "db:redis"
    - "consul:consul"
  command: nodemon -L app/bin/www

nginx:
  restart: always
  build: ./nginx
  ports:
    - "80:80"
  links:
#    - web:web
    - consul:consul
  environment:
    - "SERVICE:web"

consul:
  image: progrium/consul
  name: "node1"
  hostname: "node1"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  volumes:
    - "/ui"
  command: "-server -bootstrap -ui-dir /ui"

db:
  image: redis